global:

jt1078:
  enable: true

  intercom:
    enable: true # 是否启用 用于双向对讲
    jt1078webrtc:
      port: 10020 # 对讲默认udp端口
      ip: 124.221.30.46 # 外网ip 用于SDP协商修改
    audioPorts: [10000, 10010] # 音频端口 [min,max]
    onjoinurl: "http://127.0.0.1:10011/api/v1/join-audio" # 设备连接到音频端口的回调

  simulations:
    # jt1078文件 默认循环发送
      - name: ../testdata/data.txt
        addr: 127.0.0.1:1078 # 模拟实时
      - name: ../testdata/data.txt
        addr: 127.0.0.1:1079 # 模拟回放

  realtime: # 实时视频
    addr: '0.0.0.0:1078'
    onjoinurl: "http://127.0.0.1:10011/api/v1/real-time-join"
    onleaveurl: "http://127.0.0.1:10011/api/v1/real-time-leave"
    prefix: "live/jt1078" # 默认自定义前缀-手机号-通道 如：live/jt1078-295696659617-1

  playback: # 回放视频
    addr: '0.0.0.0:1079'
    onjoinurl: "http://127.0.0.1:10011/api/v1/play-back-join"
    onleaveurl: "http://127.0.0.1:10011/api/v1/play-back-leave"
    prefix: "live/jt1079" # 默认自定义前缀-手机号-通道 如：live/jt1079-295696659617-1

mp4:
  enable: true
