global:
  publish:
    publish_timeout: 30s  # 将无数据超时改为30秒
  http:
    listen_addr: :11080
  tcp:
    listen_addr: :11081

jt1078:
  enable: true

  intercom:
    enable: false # 是否启用 用于双向对讲
    jt1078webrtc:
      port: 11020 # 对讲默认udp端口
      ip: 124.221.30.46 # 外网ip 用于SDP协商修改
    audio_ports: [11021, 11050] # 音频端口 [min,max]
    on_join_url: "http://127.0.0.1:11000/api/v1/jt808/event/join-audio" # 设备连接到音频端口的回调
    overtime_second: 60 # 多久没有下发对讲语音的数据 就关闭这个链接

  realtime: # 实时视频
    addr: '0.0.0.0:11051'
    on_join_url: "http://127.0.0.1:11000/api/v1/jt808/event/real-time-join"
    on_leave_url: "http://127.0.0.1:11000/api/v1/jt808/event/real-time-leave"
    prefix: "live/jt1078" # 默认自定义前缀-手机号-通道 如：live/jt1078-295696659617-1
    overtime_second: 30 # 无人订阅的情况 多久就关闭这个链接（小于等于0则不启用 默认0 推荐还是使用9102指令去触发关闭)

  playback: # 回放视频
    addr: '0.0.0.0:11052'
    on_join_url: "http://127.0.0.1:11000/api/v1/play-back-join"
    on_leave_url: "http://127.0.0.1:11000/api/v1/play-back-leave"
    prefix: "live/jt1079" # 默认自定义前缀-手机号-通道 如：live/jt1079-295696659617-1
    overtime_second: 0 # 无人订阅的情况 多久就关闭这个链接（小于等于0则不启用 默认0 推荐还是使用9102指令去触发关闭)

  simulations:
    # jt1078文件 默认循环发送
    - name: ../testdata/data.txt
      addr: "127.0.0.1:11051" # 模拟实时

mp4:
  enable: true

