global:
  http:
    listenaddr: :11080
  tcp:
    listenaddr: :11081

jt1078:
  enable: true

  intercom:
    enable: false # 是否启用 用于双向对讲
    jt1078webrtc:
      port: 11020 # 对讲默认udp端口
      ip: 124.221.30.46 # 外网ip 用于SDP协商修改
    audioports: [11021, 11050] # 音频端口 [min,max]
    onjoinurl: "http://127.0.0.1:11000/api/v1/jt808/event/join-audio" # 设备连接到音频端口的回调

  realtime: # 实时视频
    addr: '0.0.0.0:11051'
    onjoinurl: "http://127.0.0.1:11000/api/v1/jt808/event/real-time-join"
    onleaveurl: "http://127.0.0.1:11000/api/v1/jt808/event/real-time-leave"
    prefix: "live/jt1078" # 默认自定义前缀-手机号-通道 如：live/jt1078-295696659617-1

  playback: # 回放视频
    addr: '0.0.0.0:11052'
    onjoinurl: "http://127.0.0.1:11000/api/v1/play-back-join"
    onleaveurl: "http://127.0.0.1:11000/api/v1/play-back-leave"
    prefix: "live/jt1079" # 默认自定义前缀-手机号-通道 如：live/jt1079-295696659617-1

mp4:
  enable: true
